package com.example.demo.routes;

import org.apache.camel.builder.RouteBuilder;
import org.springframework.stereotype.Component;

import com.example.demo.processor.MyTransformProcessor;

@Component
public class FTPRetryRoute extends RouteBuilder{

	@Override
	public void configure() throws Exception {
		
		/*onException(org.apache.camel.Component.file.)
		.log("in exception")
		.to("ftpRetryRoute");*/		
		// TODO Auto-generated method stub
		//from("ftp:{{ftp.opentext.orders.server}}:{{ftp.opentext.orders.port}}{{ftp.opentext.orders.excelorderspickuplocation}}?include=XLS.*.csv&move={{ftp.opentext.orders.excelorderspickuplocation}}/Backup&password={{ftp.opentext.orders.password}}&username={{ftp.opentext.orders.username}}&maximumReconnectAttempts=10")
		//from("ftp:{{ftp.opentext.orders.server}}:{{ftp.opentext.orders.port}}{{ftp.opentext.orders.excelorderspickuplocation}}?include=XLS.*.csv&doneFileName=${file:name}.go&move={{ftp.opentext.orders.excelorderspickuplocation}}/Backup&password={{ftp.opentext.orders.password}}&username={{ftp.opentext.orders.username}}&passiveMode=true&disconnect=true&maximumReconnectAttempts=10")
		//from("ftp:HKHKOAPP34.hk.oup.com:23/ExcelOrders/Test/retrytest/?include=XLS.*.csv&doneFileName=${file:name}.go&move=/ExcelOrders/Test/retrytest/Backup&password=hkhkoapp34FTP&username=edi&passiveMode=true&disconnect=true")
		//.routeId("ftpRetryRoute")
		//.log("In ftp retry route")
		//.log(LoggingLevel.INFO,"oup.excelchina","Polled the file ${header.CamelFileName} from FTP generated by excel ordering")
		//.convertBodyTo(String.class, "BIG5")
		//.wireTap(sourceFileBackupEndpoint)
		//.wireTap("seda:idocTransformer")
		//.process(new MyTransformProcessor())
		//.log("Deleting .go file");
	}
}
